#!/bin/bash

# Script para aplicar correção no Supabase via SQL Editor
echo "🔧 CORREÇÃO CRÍTICA: Contador de Dias da Assinatura"
echo "=================================================="
echo ""
echo "🐛 PROBLEMA IDENTIFICADO:"
echo "A função check_subscription_status() não retorna 'days_remaining' para assinaturas ativas."
echo "Por isso o contador mostra 0 dias após o pagamento PIX."
echo ""
echo "🎯 SOLUÇÃO:"
echo "Execute o SQL abaixo no Dashboard do Supabase:"
echo ""
echo "🌐 URL: https://supabase.com/dashboard/project/kmcaaqetxtwkdcczdomw/sql"
echo ""
echo "📋 SQL PARA EXECUTAR:"
echo "===================="
cat fix-days-remaining.sql
echo ""
echo "===================="
echo ""
echo "📝 INSTRUÇÕES:"
echo "1. Acesse: https://supabase.com/dashboard/project/kmcaaqetxtwkdcczdomw/sql"
echo "2. Cole o SQL acima no editor"
echo "3. Clique em 'Run' para executar"
echo "4. Verifique se a função foi atualizada"
echo ""
echo "🧪 TESTE APÓS EXECUÇÃO:"
echo "No SQL Editor, execute:"
echo "SELECT check_subscription_status('seu-email@exemplo.com');"
echo ""
echo "✅ RESULTADO ESPERADO:"
echo "Deve retornar 'days_remaining' com o número correto de dias restantes."
