#!/bin/bash

echo "🚀 DEPLOY MANUAL - MÓDULO CAIXA SUPABASE"
echo "========================================"
echo ""
echo "Como as tabelas já foram verificadas e existem, vamos confirmar:"
echo ""

# Verificar se node está disponível
if command -v node &> /dev/null; then
    echo "📋 Executando verificação final..."
    node verify-caixa-tables.cjs
else
    echo "⚠️  Node.js não encontrado, pulando verificação automática"
fi

echo ""
echo "🎯 INSTRUÇÕES PARA DEPLOY MANUAL (se necessário):"
echo "================================================="
echo ""
echo "1. 🌐 Acesse o Dashboard do Supabase:"
echo "   https://supabase.com/dashboard/project/kmcaaqetxtwkdcczdomw/sql"
echo ""
echo "2. 📄 Cole o SQL abaixo no editor:"
echo ""
echo "-- Criar tabelas do módulo Caixa"
echo "CREATE TABLE IF NOT EXISTS public.caixa ("
echo "    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,"
echo "    usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,"
echo "    valor_inicial DECIMAL(10,2) NOT NULL DEFAULT 0.00,"
echo "    valor_final DECIMAL(10,2) DEFAULT NULL,"
echo "    data_abertura TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,"
echo "    data_fechamento TIMESTAMP WITH TIME ZONE DEFAULT NULL,"
echo "    status TEXT CHECK (status IN ('aberto', 'fechado')) DEFAULT 'aberto',"
echo "    diferenca DECIMAL(10,2) DEFAULT NULL,"
echo "    observacoes TEXT,"
echo "    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,"
echo "    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL"
echo ");"
echo ""
echo "CREATE TABLE IF NOT EXISTS public.movimentacoes_caixa ("
echo "    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,"
echo "    caixa_id UUID NOT NULL REFERENCES public.caixa(id) ON DELETE CASCADE,"
echo "    tipo TEXT CHECK (tipo IN ('entrada', 'saida')) NOT NULL,"
echo "    descricao TEXT NOT NULL,"
echo "    valor DECIMAL(10,2) NOT NULL,"
echo "    usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,"
echo "    venda_id UUID DEFAULT NULL,"
echo "    data TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,"
echo "    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL"
echo ");"
echo ""
echo "-- Desabilitar RLS"
echo "ALTER TABLE public.caixa DISABLE ROW LEVEL SECURITY;"
echo "ALTER TABLE public.movimentacoes_caixa DISABLE ROW LEVEL SECURITY;"
echo ""
echo "-- Criar índices"
echo "CREATE INDEX IF NOT EXISTS idx_caixa_usuario ON public.caixa(usuario_id);"
echo "CREATE INDEX IF NOT EXISTS idx_caixa_status ON public.caixa(status);"
echo "CREATE INDEX IF NOT EXISTS idx_movimentacoes_caixa_id ON public.movimentacoes_caixa(caixa_id);"
echo "CREATE INDEX IF NOT EXISTS idx_movimentacoes_tipo ON public.movimentacoes_caixa(tipo);"
echo ""
echo "3. ▶️  Clique em 'Run' para executar"
echo ""
echo "4. ✅ Aguarde as mensagens de confirmação"
echo ""
echo "🎉 RESULTADO ESPERADO:"
echo "====================="
echo "✅ Todas as tabelas criadas com sucesso"
echo "✅ Módulo Caixa funcionando perfeitamente"
echo "✅ Sistema PDV operacional"
echo ""
echo "🚀 Teste final: https://pdv-allimport.vercel.app"
echo ""
echo "📱 Vá em Caixa → Abrir Caixa → Digite valor → Confirmar"
echo "   Deve funcionar sem erros!"
