-- 🗑️ LIMPAR COMPLETAMENTE TODOS OS DADOS DO BACKUP ALLIMPORT

-- REMOVER TODOS OS DADOS INSERIDOS DO BACKUP

-- 1. REMOVER PRODUTOS ALLIMPORT DA TABELA 'products'
DELETE FROM products WHERE name LIKE 'ALLIMPORT%';

-- 2. REMOVER PRODUTOS ALLIMPORT DA TABELA 'produtos' (se existirem)
DELETE FROM produtos WHERE nome LIKE 'ALLIMPORT%';

-- 3. REMOVER CATEGORIAS ALLIMPORT DA TABELA 'categories'
DELETE FROM categories WHERE name LIKE 'ALLIMPORT%';

-- 4. REMOVER CATEGORIAS ALLIMPORT DA TABELA 'categorias' (se existirem)
DELETE FROM categorias WHERE nome LIKE 'ALLIMPORT%';

-- 5. REMOVER CLIENTES ALLIMPORT DA TABELA 'clients'
DELETE FROM clients WHERE name LIKE '%ALLIMPORT%';

-- 6. REMOVER CLIENTES ALLIMPORT DA TABELA 'clientes' (se existirem)
DELETE FROM clientes WHERE nome LIKE '%ALLIMPORT%';

-- 7. REMOVER ORDENS DE SERVIÇO COM EQUIPAMENTOS ALLIMPORT
DELETE FROM service_orders WHERE equipment LIKE '%EQUIPAMENTO%' AND created_at > '2025-08-19';

-- VERIFICAR LIMPEZA
SELECT 'LIMPEZA CONCLUÍDA - VERIFICAÇÃO:' as resultado;
SELECT 'products' as tabela, COUNT(*) as restantes FROM products WHERE name LIKE 'ALLIMPORT%'
UNION ALL
SELECT 'produtos', COUNT(*) FROM produtos WHERE nome LIKE 'ALLIMPORT%'  
UNION ALL
SELECT 'categories', COUNT(*) FROM categories WHERE name LIKE 'ALLIMPORT%'
UNION ALL  
SELECT 'clients', COUNT(*) FROM clients WHERE name LIKE '%ALLIMPORT%';

-- ✅ TODOS OS DADOS DO BACKUP FORAM REMOVIDOS!
-- O banco voltou ao estado anterior ao backup
