-- 🔍 VERIFICAR SE OS DADOS DO BACKUP FORAM INSERIDOS

-- 1. CONTAR TODOS OS PRODUTOS
SELECT 'TOTAL DE PRODUTOS:' as info, COUNT(*) as quantidade FROM products;

-- 2. VERIFICAR SE OS PRODUTOS DA ALLIMPORT ESTÃO LÁ
SELECT 'PRODUTOS ALLIMPORT ENCONTRADOS:' as info;
SELECT name FROM products 
WHERE name IN (
    'WIRELESS MICROPHONE',
    'CABO USB TIPO C', 
    'BATERIA SMARTPHONE',
    'TELA TOUCH SCREEN',
    'CARREGADOR ORIGINAL'
) 
ORDER BY name;

-- 3. LISTAR TODOS OS PRODUTOS (para verificar o que existe)
SELECT 'TODOS OS PRODUTOS:' as info;
SELECT name FROM products ORDER BY created_at DESC LIMIT 20;

-- 4. VERIFICAR SE FORAM INSERIDOS RECENTEMENTE
SELECT 'PRODUTOS RECENTES:' as info;
SELECT name, created_at FROM products 
WHERE created_at > NOW() - INTERVAL '1 hour'
ORDER BY created_at DESC;

-- 5. BUSCAR POR PALAVRAS-CHAVE DA ALLIMPORT
SELECT 'BUSCA POR PALAVRAS-CHAVE:' as info;
SELECT name FROM products 
WHERE UPPER(name) LIKE '%WIRELESS%' 
   OR UPPER(name) LIKE '%MICROPHONE%'
   OR UPPER(name) LIKE '%BATERIA%'
   OR UPPER(name) LIKE '%TELA%'
ORDER BY name;
