name: Debug Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Debug - Check files
      run: |
        echo "=== Repository Contents ==="
        ls -la
        echo "=== Package.json exists? ==="
        ls -la package.json || echo "package.json not found"
        echo "=== Node version ==="
        node --version
        echo "=== NPM version ==="
        npm --version
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Dependencies installed successfully"
    
    - name: Debug - Check dist before build
      run: |
        echo "=== Before build ==="
        ls -la
        echo "=== Dist folder exists? ==="
        ls -la dist/ || echo "dist folder not found"
    
    - name: Build with debug
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed"
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        VITE_SUPABASE_URL: https://kmcaaqetxtwkdcczdomw.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttY2FhcWV0eHR3a2RjY3pkb213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjU3MDksImV4cCI6MjA2OTUwMTcwOX0.gFcUOoNPESqp2PALV5CYhMceTQ4HVuf-noGn94Fzbwg
        VITE_APP_NAME: "PDV Allimport"
        VITE_APP_URL: https://raidosystem.github.io/Pdv-Allimport
    
    - name: Debug - Check dist after build
      run: |
        echo "=== After build ==="
        ls -la dist/
        echo "=== Index.html content ==="
        head -20 dist/index.html
        echo "=== Check for Supabase config in JS ==="
        grep -r "kmcaaqetxtwkdcczdomw" dist/ || echo "Supabase URL not found in build"
